# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abbcbad0bb32ca19b089252f538cf261290a5eb9652d440c228bd5c18a2b4f71a1032826cc38ddd782f57b7d8b3dd7bdc668ed10bbee93869151bc623276a796

test:
  secret_key_base: f4a932de9caf3aabc604565590d5f4cc464b21da871303c4a629dbe5012e704599d88e5407aeca8b04c4ec220a7f6e47c969d967656a72298901036defdc577c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
